services:
    - type: web
      name: studentio-backend
      env: docker
      plan: free
      healthCheckPath: /health
      autoDeploy: true
      envVars:
          - key: OPENAI_API_KEY
            sync: false
          - key: OPENAI_MODEL
            value: gpt-4o-mini
          - key: ALLOW_ORIGINS
            value: https://studentio-bot.vercel.app,http://localhost:3000
